name: my_chat_app
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    supabase_flutter: ^2.9.1
    flutter_local_notifications: any # 알림 패키지 추가
    flutter_local_notifications_windows: any # Windows 알림 플러그인 추가

    flutter_dotenv: ^5.2.1
    shared_preferences: ^2.2.3
    uuid: ^4.4.0
    intl: ^0.19.0
    provider: ^6.1.2
    emoji_picker_flutter: ^4.3.0 # 이모티콘 선택기 패키지 추가
    image_picker: ^1.0.0 # 이미지 선택 패키지 추가

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
    fonts:
        - family: NotoSansKR
          fonts:
              - asset: assets/fonts/NotoSansKR-Regular.ttf
              - asset: assets/fonts/NotoSansKR-Bold.ttf
                weight: 700
              - asset: assets/fonts/NotoSansKR-Light.ttf
                weight: 300
